language: python
cache: yarn
install:
  - yarn install

script:
  - yarn test
  - yarn run build

deploy:
  provider: pages
  skip_cleanup: true
  github-token: $GITHUB_TOKEN
  on:
    branch: gh-pages

